### ISSUE TITLE
Tags dialogue raises error if MetaDataModel contains unsupported types

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-gui-tk#23]
Error message below:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\tkgui.py", line 1368, in _edit_tags_event
    self.edit_tags()
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\tkgui.py", line 1376, in edit_tags
    self.dataset_list_model.get_active_uri()
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\tkgui.py", line 1090, in __init__
    edit_tags_frame = EditTagsFrame(self, master, dataset_uri)
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\tkgui.py", line 994, in __init__
    self.dataset_model.load_dataset(dataset_uri)
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\models.py", line 601, in load_dataset
    self._metadata_model = metadata_model_from_dataset(self._dataset)
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\models.py", line 82, in metadata_model_from_dataset
    _type = get_json_schema_type(value)
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\models.py", line 43, in get_json_schema_type
    raise(UnsupportedTypeError("{} not supported yet".format(type(obj))))
dtool_gui_tk.models.UnsupportedTypeError: <class 'ruamel.yaml.comments.CommentedMap'> not supported yet
```

**Comment by tjelvar-olsson** [comment]
Fixed in e33ce9c
