### ISSUE TITLE
Error when clicking DataSetListFrame headers when no datasets present in base URI

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-gui-tk#25]
Error message:

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\tkgui.py", line 199, in sort_by_num_items
    self._sort("num_items")
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\tkgui.py", line 189, in _sort
    self.root.dataset_list_model.sort(self._sort_key, self._reverse_sort_order)  # NOQA
  File "c:\users\olssont\envs\mega\lib\site-packages\dtool_gui_tk\models.py", line 957, in sort
    _, self._datasets, self._datasets_info = [list(t) for t in tuples]
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by tjelvar-olsson** [comment]
Fixed in 5e1f9c0
